### ISSUE TITLE
Issue in ValidateSignatureMethodStrength - ASP.net web forms

### ISSUE THREAD

**Issue by tkamesh08** [KentorIT/authservices#672]
I have configured OKTA as IDP and i can see the successful login message in OKTA log for each login attempt from  my application. But i am getting  the following error message in event viewer. can anyone please help me on this

Exception information: 
    Exception type: InvalidSignatureException 
    Exception message: **The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted http://www.w3.org/2000/09/xmldsig#rsa-sha1.**
   at Kentor.AuthServices.XmlHelpers.ValidateSignatureMethodStrength(String minIncomingSignatureAlgorithm, String signatureMethod)
   at Kentor.AuthServices.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Kentor.AuthServices.Saml2P.Saml2Response.ValidateSignature(IOptions options)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: https://localhost/hr/AuthServices/Acs 
    Request path: /AuthServices/Acs 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\hr 
 
Thread information: 
    Thread ID: 7 
    Thread account name: IIS APPPOOL\hr 
    Is impersonating: False 
    Stack trace:    at Kentor.AuthServices.XmlHelpers.ValidateSignatureMethodStrength(String minIncomingSignatureAlgorithm, String signatureMethod)
   at Kentor.AuthServices.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Kentor.AuthServices.Saml2P.Saml2Response.ValidateSignature(IOptions options)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by AndersAbel** [comment]
This is a bug in the new code of v0.20.0 that compares the signatures. I'll have a look and try to get a fix done ASAP.

**Comment by AndersAbel** [comment]
What .NET version are you running on? It might be an incorrect error message if you run on a framework version that doesn't support SHA256 signatures.

**Comment by AndersAbel** [comment]
Looks like this a non-critical bug in the error handling. The error message that SHA256 is weaker than SHA1 is incorrectly thrown when SHA256 is a non-recognized algorithm. The correct error message should be "SHA256 signatures require the algorithm to be registered at the process level. Upgrade to .Net 4.6.2 or call Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures() on startup to register." This will be fixed in the next release of AuthServices.

**Comment by etortec** [comment]
It seems to me that the Options.GlobalEnableSha256XmlSignatures() 'workaround' to allow processing of SHA256 based signatures in .Net 4.5 is broken somehow in v.0.20.0:

We’re using Kentor.Authservices with Options.GlobalEnableSha256XmlSignatures() to allow processing of IDP responses signed with SHA256 in an OWIN project running targeting .Net 4.5. 

After upgrading from v0.19.0 to v0.20.0 we receive the in the first post reported exception during processing of the IDP auth response, even though we are using Options.GlobalEnableSha256XmlSignatures() to register the SHA256 signature algorithm. 

Reverting the nuget package version of Kentor.AuthServices back to v0.19.0 allows AuthServices to successfully verify a SHA256 based signature again.

Note that this problem only occurs on an environment that has .Net 4.5 installed. On another system with .Net 4.6.2 everything works as expected.

**Comment by AndersAbel** [comment]
@etortec Yes, you confirm what I've expected after looking through the code. There is a bug in AuthServices v0.20.0 that breaks `GlobalEnableSha256XmlSignatures()`. A fix will be released during the next few days, but for now, you will have to revert to 0.19.0.

**Comment by tkamesh08** [comment]
@AndersAbel thanks for you help. I upgraded the server to .net framework 4.6, now the issue has been resolved.

**Comment by AndersAbel** [comment]
@etortec  @tkamesh08 This is now fixed in the source, If anyone still running on .NET 4.5.2 would be able to test this before release I'd be grateful.

**Comment by etortec** [comment]
@AndersAbel  I did a quick test and it appears the problem is not yet fixed. I now get the following exception:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Kentor.AuthServices.XmlHelpers.GetCorrespondingDigestAlgorithm(String signingAlgorithm) in C:\Temp\authservices-master\Kentor.AuthServices\XmlHelpers.cs:line 602
   at Kentor.AuthServices.XmlHelpers.ValidateSignedInfo(SignedXml signedXml, XmlElement xmlElement, String minIncomingSignatureAlgorithm) in C:\Temp\authservices-master\Kentor.AuthServices\XmlHelpers.cs:line 382
   at Kentor.AuthServices.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm) in C:\Temp\authservices-master\Kentor.AuthServices\XmlHelpers.cs:line 246
   at Kentor.AuthServices.Saml2P.Saml2Response.<>c__DisplayClass52_0.<ValidateSignature>b__0(XmlElement a) in C:\Temp\authservices-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 459
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Kentor.AuthServices.Saml2P.Saml2Response.ValidateSignature(IOptions options) in C:\Temp\authservices-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 457
   at Kentor.AuthServices.Saml2P.Saml2Response.Validate(IOptions options) in C:\Temp\authservices-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 432
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext() in C:\Temp\authservices-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 506
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options) in C:\Temp\authservices-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 502
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) in C:\Temp\authservices-master\Kentor.AuthServices\WebSso\AcsCommand.cs:line 93
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) in C:\Temp\authservices-master\Kentor.AuthServices\WebSso\AcsCommand.cs:line 81
   at Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext() in C:\Temp\authservices-master\Kentor.AuthServices.Owin\KentorAuthServicesAuthenticationHandler.cs:line 28
```

Looking at the code it seems GlobalEnableSha256XmlSignatures() now adds `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` to the `XmlHelpers.KnownSigningAlgorithms`, but `XmlHelpers.digestAlgorithms` still only contains `http://www.w3.org/2000/09/xmldsig#rsa-sha1` in .Net 4.5 and thus we fail to find a match.

**Comment by AndersAbel** [comment]
@etortec Thanks. You're right, I forgot about digestAlgorithms...

**Comment by AndersAbel** [comment]
Fixed including digestAlgorithms this time. @etortec would you mind testing again if you have a .NET 4.5.2. machine availabe?

**Comment by etortec** [comment]
@AndersAbel I retested with your latest change from master and both validation and creation of RSA-SHA256 signatures now work on .Net 4.5.

Thanks a lot for your quick response!

**Comment by AndersAbel** [comment]
@etortec Thanks for the help with testing. I don't have any machine with .NET 4.5 available. That's why this slipped through, it isn't properly tested as the rest of the code.

**Comment by explunit** [comment]
I was looking for the appveyor configuration to see if this could be done with an appveyor matrix configuration, but it doesn't seem to be part of the repo.

**Comment by AndersAbel** [comment]
@explunit The appveyor config is done in the web interface, because it contains API keys. I'll see if I can give you access.

**Comment by explunit** [comment]
It seems this is not possible on appveyor platform, but we'll see if someone responds to correct my understanding: http://help.appveyor.com/discussions/questions/3572-run-tests-on-older-net-versions

**Comment by abilash1205** [comment]
hai i am getting same error in .net framwork 4.5 and  i used Kentor.AuthServices v0.21.0
