### ISSUE TITLE
Exception message is incorrect when SHA-256 is not supported

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#717]
If running on .Net versions prior to 4.6.2 and you have **not** called `GlobalEnableSha256XmlSignatures()` the message when a Sha256 signature arrives is
>  "The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted http://www.w3.org/2000/09/xmldsig#rsa-sha1."

The message should be:
> "SHA256 signatures require the algorithm to be registered at the process level. Upgrade to .Net 4.6.2 or call Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures() on startup to register."

**Comment by lstaerkmagui** [comment]
I have been getting this error in .NET 4.6.2 as well. I have also tried calling GlobalEnableSha256XmlSignatures() before checking the SAML response signature and I also received this error.

**Comment by explunit** [comment]
can you paste the exact error message you are seeing on 4.6.2?

**Comment by AndersAbel** [comment]
@lstaerkmagui Are you sure you've got **exactly** that error message on 4.6.2? Please check again, I'd guess you get the algorithm names the other way around.

**Comment by AndersAbel** [comment]
@explunit so now it's proven, You're 10 seconds faster on the keyboard than I am ;-)

**Comment by lstaerkmagui** [comment]
@AndersAbel You are correct! Sorry to bother you guys.

**Comment by abilash1205** [comment]
i am getting below error

The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted http://www.w3.org/2000/09/xmldsig#rsa-sha1.

i used below kentor authservices in okta

http://developer.okta.com/blog/2016/03/22/use-kentor-authservices-with-okta/

in mvc i used latest kentor V0.21.2

visual studio 2012 framework 4.5

can please help on this

**Comment by abilash1205** [comment]
i added
public static class AuthConfig
    {
        public static void RegisterAuth()
        {
            Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures();
        }
    }

**Comment by abilash1205** [comment]
<configSections>
    <section name="system.identityModel" type="System.IdentityModel.Configuration.SystemIdentityModelSection, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
    <section name="system.identityModel.services" type="System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
    <section name="kentor.authServices" type="Kentor.AuthServices.Configuration.KentorAuthServicesSection, Kentor.AuthServices" />
  </configSections>

  <system.web>
    <httpRuntime targetFramework="4.5" />
    <compilation debug="true" targetFramework="4.5" />
    <authentication mode="Forms">
      <forms loginUrl="~/AuthServices/SignIn" timeout="2880" />
    </authentication>
    <pages>
      <namespaces>
        <add namespace="System.Web.Helpers" />
        <add namespace="System.Web.Mvc" />
        <add namespace="System.Web.Mvc.Ajax" />
        <add namespace="System.Web.Mvc.Html" />
        <add namespace="System.Web.Optimization" />
        <add namespace="System.Web.Routing" />
        <add namespace="System.Web.WebPages" />
      </namespaces>
    </pages>
    <profile defaultProvider="DefaultProfileProvider">
      <providers>
        <add name="DefaultProfileProvider" type="System.Web.Providers.DefaultProfileProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" applicationName="/" />
      </providers>
    </profile>
    <membership defaultProvider="DefaultMembershipProvider">
      <providers>
        <add name="DefaultMembershipProvider" type="System.Web.Providers.DefaultMembershipProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" requiresUniqueEmail="false" maxInvalidPasswordAttempts="5" minRequiredPasswordLength="6" minRequiredNonalphanumericCharacters="0" passwordAttemptWindow="10" applicationName="/" />
      </providers>
    </membership>
    <roleManager defaultProvider="DefaultRoleProvider">
      <providers>
        <add name="DefaultRoleProvider" type="System.Web.Providers.DefaultRoleProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" applicationName="/" />
      </providers>
    </roleManager>
    
    <sessionState mode="InProc" customProvider="DefaultSessionProvider">
      <providers>
        <add name="DefaultSessionProvider" type="System.Web.Providers.DefaultSessionStateProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" />
      </providers>
    </sessionState>
  </system.web>
  <kentor.authServices entityId="http://localhost:53761/AuthServices" returnUrl="http://localhost:53761/Home" publicOrigin="http://localhost:53761/AuthServices/SignIn">
    
    <identityProviders>
      <add entityId="http://www.okta.com/exkaet221dhc01PD80h7" signOnUrl="https://dev-128899.oktapreview.com/app/techdev128899_test12_1/exkaet221dhc01PD80h7/sso/saml" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/okta.cer" />
      </add>
    </identityProviders>
  </kentor.authServices>

  <system.identityModel>
    <identityConfiguration>
      <audienceUris>
        <add value="http://localhost:53761/AuthServices" />
      </audienceUris>
    </identityConfiguration>
  </system.identityModel>

  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="MvctestoktaAuth" />
    </federationConfiguration>
  </system.identityModel.services>
  <system.webServer>

    <validation validateIntegratedModeConfiguration="false" />
    <modules>
      
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      
      
    </modules>

  </system.webServer>
 

</configuration>

**Comment by AndersAbel** [comment]
@abilash1205 Please don't just dump your code and config here.

If you are on .NET 4.5 that error message is a bit misleading. Add a call to `Options.GlobalEnableSha256Signatures()` to enable SHA256 support.

**Comment by abilash1205** [comment]
thank you issuse is solved

**Comment by brillox** [comment]
I still get the message and I have just upgraded all my c# project filers to use 4.6.2 which is also installed on my test server:

The signing algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 is weaker than the minimum accepted http://www.w3.org/2001/04/xmldsig-more#rsa-sha256.

**Comment by brillox** [comment]
InvalidSignatureException: The signing algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 is weaker than the minimum accepted http://www.w3.org/2001/04/xmldsig-more#rsa-sha256.]
   Kentor.AuthServices.XmlHelpers.ValidateSignatureMethodStrength(String minIncomingSignatureAlgorithm, String signatureMethod) +259
   Kentor.AuthServices.XmlHelpers.ValidateSignedInfo(SignedXml signedXml, XmlElement xmlElement, String minIncomingSignatureAlgorithm) +29
   Kentor.AuthServices.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm) +95
   Kentor.AuthServices.Saml2P.<>c__DisplayClass52_0.<ValidateSignature>b__0(XmlElement a) +38
   System.Linq.Enumerable.Any(IEnumerable`1 source, Func`2 predicate) +146
   Kentor.AuthServices.Saml2P.Saml2Response.ValidateSignature(IOptions options) +212
   Kentor.AuthServices.Saml2P.<CreateClaims>d__57.MoveNext() +91
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +387
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options) +90
   Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState) +38
   Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) +441
   Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) +261
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

**Comment by explunit** [comment]
@brillox in your case the message is correct. On .Net 4.6.2 the default is to require SHA256 unless you specifically configure it for downgrade.

**Comment by brillox** [comment]
OK thanks and how I can configure this in web config?

**Comment by explunit** [comment]
@brillox https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#minincomingsigningalgorithm-attribute

**Comment by brillox** [comment]
Thanks explunit, I appreciate your help; the problem is that I have inherited an application that use Kentor but I haven't used at all before and the guy who left did not wrote any documentation; if I am not arsing too much could you please give me a snippet of  a web config with those attributes so that I can figure it out where to add it to the existing web config? Apologies for asking for this but at the moment I am not updating to the latest kentor only for this reason

**Comment by explunit** [comment]
@brillox https://github.com/KentorIT/authservices/blob/v0.21.2/Kentor.AuthServices.Tests/App.config#L8-L9

**Comment by brillox** [comment]
what can I say... you are a star? Thanks a lot!!
